apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  name: boot-sample-ingress
  namespace: zmon
spec:
  rules:
  - host: boot-sample.zmon-dev.seo01.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: boot-sample-service
          servicePort: 8080
        path: /
